### ISSUE TITLE
Cannot delete non-world-writeable gems on cache purge

### ISSUE THREAD

**Issue by schneems** [heroku/heroku-buildpack-ruby#1049]
When someone upgrades Ruby versions we purge the cache by deleting the directory. Unfortunatly some gems can have different permissions which cause `FileUtils.rmdir` to fail. For instance minitest:

```
$ git push heroku
Enumerating objects: 8, done.
Counting objects: 100% (8/8), done.
Delta compression using up to 8 threads
Compressing objects: 100% (7/7), done.
Writing objects: 100% (8/8), 735 bytes | 735.00 KiB/s, done.
Total 8 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Ruby app detected
remote: -----> Installing bundler 2.0.2
remote: -----> Removing BUNDLED WITH version in the Gemfile.lock
remote: -----> Compiling Ruby
remote: -----> Using Ruby version: ruby-2.6.6
remote: -----> Installing dependencies using bundler 2.0.2
remote:        Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
remote:        Fetching gem metadata from https://rubygems.org/.
remote:        Fetching rake 13.0.1
remote:        Installing rake 13.0.1
remote:        Using bundler 2.0.2
remote:        Fetching minitest 5.14.1
remote:        Installing minitest 5.14.1
remote:        Bundle complete! 2 Gemfile dependencies, 3 gems now installed.
remote:        Gems in the groups development and test were not installed.
remote:        Bundled gems are installed into `./vendor/bundle`
remote:        Bundle completed (1.55s)
remote:        Cleaning up the bundler cache.
remote: -----> Detecting rake tasks
remote:
remote: ###### WARNING:
remote:
remote:        You have not declared a Ruby version in your Gemfile.
remote:
remote:        To declare a Ruby version add this line to your Gemfile:
remote:
remote:        ```
remote:        ruby "2.6.6"
remote:        ```
remote:
remote:        For more information see:
remote:          https://devcenter.heroku.com/articles/ruby-versions
remote:
remote: ###### WARNING:
remote:
remote:        No Procfile detected, using the default web server.
remote:        We recommend explicitly declaring how to boot your server process via a Procfile.
remote:        https://devcenter.heroku.com/articles/ruby-default-web-server
remote:
remote:
remote: -----> Discovering process types
remote:        Procfile declares types     -> (none)
remote:        Default types for buildpack -> console, rake
remote:
remote: -----> Compressing...
remote:        Done: 13M
remote: -----> Launching...
remote:        Released v4
remote:        https://immense-retreat-19858.herokuapp.com/ deployed to Heroku
remote:
remote: Verifying deploy... done.
To https://git.heroku.com/immense-retreat-19858.git
 * [new branch]      main -> main
⛄ 2.7.1 🚀  /tmp/3eeccadff03adc444afc1208b0a3e4ce (main)
$ heroku run bash
Running bash on ⬢ immense-retreat-19858... up, run.1224 (Free)
~ $ rm -r vendor/bundle/
rm: remove write-protected regular file 'vendor/bundle/ruby/2.6.0/gems/minitest-5.14.1/test/minitest/test_minitest_reporter.rb'?
rm: remove write-protected regular file 'vendor/bundle/ruby/2.6.0/gems/minitest-5.14.1/test/minitest/test_minitest_benchmark.rb'? ir^C
~ $ ^C
~ $ irb
irb(main):001:0> FileUtils.rmdir("vendor/bundle")
Traceback (most recent call last):
        8: from /app/bin/irb:30:in `<main>'
        7: from /app/bin/irb:30:in `load'
        6: from /app/vendor/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        5: from (irb):1
        4: from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/fileutils.rb:256:in `rmdir'
        3: from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/fileutils.rb:256:in `each'
        2: from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/fileutils.rb:257:in `block in rmdir'
        1: from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/fileutils.rb:257:in `rmdir'
Errno::ENOTEMPTY (Directory not empty @ dir_s_rmdir - vendor/bundle)
```

**Comment by schneems** [comment]
Still an issue, but not sure how it could be fixable. I think this is more an individual issue with each gem that has a non-world-writeable file
