### ISSUE TITLE
Getting bundler error since today

### ISSUE THREAD

**Issue by qortex** [heroku/heroku-buildpack-ruby#1080]
Was there any change in the build environment? My app deployment stopped working today with no significant change in my code. Reverting to previous images work, so my understanding is that the build environment somehow changed.

I now get this when starting console or test environment:

It seems related to https://github.com/rubygems/rubygems/issues/3284

Heroku ticket: https://help.heroku.com/tickets/924861

Cc @schneems 

```
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:105: warning: already initialized constant Bundler::FileUtils::VERSION
/app/vendor/ruby-2.7.1/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:105: warning: previous definition of VERSION was here
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:1284: warning: already initialized constant Bundler::FileUtils::Entry_::S_IF_DOOR
/app/vendor/ruby-2.7.1/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:1284: warning: previous definition of S_IF_DOOR was here
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:1568: warning: already initialized constant Bundler::FileUtils::Entry_::DIRECTORY_TERM
/app/vendor/ruby-2.7.1/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:1568: warning: previous definition of DIRECTORY_TERM was here
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:1626: warning: already initialized constant Bundler::FileUtils::OPT_TABLE
/app/vendor/ruby-2.7.1/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:1626: warning: previous definition of OPT_TABLE was here
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:1685: warning: already initialized constant Bundler::FileUtils::LOW_METHODS
/app/vendor/ruby-2.7.1/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:1685: warning: previous definition of LOW_METHODS was here
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:1692: warning: already initialized constant Bundler::FileUtils::METHODS
/app/vendor/ruby-2.7.1/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:1692: warning: previous definition of METHODS was here
Traceback (most recent call last):
	9: from /app/vendor/bundle/ruby/2.7.0/bin/bundle:23:in `<main>'
	8: from /app/vendor/bundle/ruby/2.7.0/bin/bundle:23:in `load'
	7: from /app/vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/exe/bundle:13:in `<top (required)>'
	6: from /app/vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/exe/bundle:13:in `require_relative'
	5: from /app/vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler.rb:7:in `<top (required)>'
	4: from /app/vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler.rb:7:in `require_relative'
	3: from /app/vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/errors.rb:3:in `<top (required)>'
	2: from /app/vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/errors.rb:20:in `<module:Bundler>'
	1: from /app/vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/errors.rb:20:in `<class:GemfileError>'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/errors.rb:9:in `status_code': Trying to register Bundler::GemfileError for status code 4 but Bundler::GemfileError is already registered (ArgumentError)
```

**Comment by qortex** [comment]
To clarify: the app starts and works just fine.
It's the testing & console that stops working. It must be related to something in my code that breaks with the new buildpack. I'll continue to investigate further and post any findings here.

**Comment by schneems** [comment]
Sorry to hear that. Can you try updating to Ruby 2.7.2 and let me know if that fixes the issue? If not, can you open a support ticket and reference this issue so I can take a closer look at your application?

**Comment by qortex** [comment]
Great! Upgrading to 2.7.2 fixes the issue. Thanks a lot.
