### ISSUE TITLE
Bundler 2.x does not work with Jruby 9.1.x (2.3.3)

### ISSUE THREAD

**Issue by schneems** [heroku/heroku-buildpack-ruby#1118]
## Repro

```
mkdir -p /tmp/5845a548ca163d550275a966f4e8e574; cd /tmp/5845a548ca163d550275a966f4e8e574

cat <<EOM> Gemfile
source 'https://rubygems.org'
gem 'rake'
EOM

cat <<EOM>Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    rake (13.0.3)

PLATFORMS
  java
  universal-java-10

DEPENDENCIES
  rake

BUNDLED WITH
   2.2.7

RUBY VERSION
   ruby 2.3.3p0 (jruby 9.1.17.0)
EOM
git init; git add .; git commit -m first
heroku create
git push heroku
```

```
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 8 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (7/7), 726 bytes | 726.00 KiB/s, done.
Total 7 (delta 0), reused 0 (delta 0), pack-reused 0
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Building on the Heroku-20 stack
remote: -----> Ruby app detected
remote: -----> Installing bundler 2.1.4
remote: -----> Removing BUNDLED WITH version in the Gemfile.lock
remote: -----> Compiling Ruby
remote: -----> Using Ruby version: ruby-2.3.3-jruby-9.1.17.0
remote: -----> Installing JVM: openjdk-8
remote: -----> Installing dependencies using bundler 2.1.4
remote:        Running: BUNDLE_WITHOUT='development:test' BUNDLE_PATH=vendor/bundle BUNDLE_BIN=vendor/bundle/bin BUNDLE_DEPLOYMENT=1 bundle install -j4
remote:        There was an error while trying to write to
remote:        `/app/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions`.
remote:        It is likely that you need to grant write permissions for that path.
remote:        Bundler Output: There was an error while trying to write to
remote:        `/app/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions`.
remote:        It is likely that you need to grant write permissions for that path.
remote:
remote:  !
remote:  !     Failed to install gems via Bundler.
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !	Push rejected to radiant-bayou-35852.
```

## Workaround

As a workaround these will fix this issue:

- Using bundler 1.x or removing the bundler version from the Gemfile.lock
- Using ruby instead of jruby
- Using jruby version 2.5.7 (9.2.13.0, Ruby Versions: [2.5.7]) instead of 2.3.3

## Debug

I've made a branch to be able to debug this issue:

```
heroku buildpacks:set https://github.com/heroku/heroku-buildpack-ruby#issues/1117
heroku buildpacks:add https://github.com/edmorley/heroku-buildpack-list-app-dir
```

Based on this debugging it appears that the issue is related to the interactions between bundler and jruby:

- https://github.com/jruby/jruby/pull/5168
- https://github.com/rubygems/bundler/issues/6532

Specificially:

```
remote:        local_path: <Pathname:/app/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions>
remote:        local_path exist: false
remote:        local_path dirname exist: true
remote:        [<Pathname:/tmp/bundler-compact-index-20210203-408-6r1ykc/versions>, <Pathname:/app/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions>]
remote:        /app/vendor/bundle/jruby/2.3.0/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb
remote:        536
remote:        bundler error: Permission denied - /tmp/bundler-compact-index-20210203-408-6r1ykc/versions or /app/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions
```

Call path:

```
remote:        /app/vendor/ruby-2.3.3-jruby-9.1.17.0/lib/ruby/stdlib/tmpdir.rb:89:in `mktmpdir'
remote:        /app/vendor/bundle/jruby/2.3.0/gems/bundler-2.1.4/lib/bundler/compact_index_client/updater.rb:31:in `update'
remote:        /app/vendor/bundle/jruby/2.3.0/gems/bundler-2.1.4/lib/bundler/compact_index_client.rb:98:in `update'
remote:        /app/vendor/bundle/jruby/2.3.0/gems/bundler-2.1.4/lib/bundler/compact_index_client.rb:85:in `update_and_parse_checksums!'
remote:        /app/vendor/bundle/jruby/2.3.0/gems/bundler-2.1.4/lib/bundler/fetcher/compact_index.rb:75:in `available?'
remote:        /app/vendor/bundle/jruby/2.3.0/gems/bundler-2.1.4/lib/bundler/fetcher/compact_index.rb:16:in `call'
remote:        /app/vendor/bundle/jruby/2.3.0/gems/bundler-2.1.4/lib/bundler/fetcher/compact_index.rb:16:in `block in available?'
remote:        /app/vendor/bundle/jruby/2.3.0/gems/bundler-2.1.4/lib/bundler/fetcher.rb:162:in `use_api'
remote:        /app/vendor/bundle/jruby/2.3.0/gems/bundler-2.1.4/lib/bundler/source/rubygems.rb:388:in `block in api_fetchers'
remote:        /app/vendor/bundle/jruby/2.3.0/gems/bundler-2.1.4/lib/bundler/source/rubygems.rb:388:in `select'
remote:        /app/vendor/bundle/jruby/2.3.0/gems/bundler-2.1.4/lib/bundler/source/rubygems.rb:388:in `api_fetchers'
remote:        /app/vendor/bundle/jruby/2.3.0/gems/bundler-2.1.4/lib/bundler/source/rubygems.rb:393:in `block in remote_specs'
remote:        /app/vendor/bundle/jruby/2.3.0/gems/bundler-2.1.4/lib/bundler/index.rb:11:in `build'
```

**Comment by schneems** [comment]
Related ticket https://heroku.support/958280

**Comment by schneems** [comment]
@enebo what's the support policy for jruby 9.1.x? I see it's not had a release since 2018.

**Comment by enebo** [comment]
@schneems 9.1 has been EOL for a while.  All users are encouraged to use 9.2.

**Comment by schneems** [comment]
Thanks!

**Comment by schneems** [comment]
Since this is EOL on JRuby's side I'm going to close the issue
