### ISSUE TITLE
Could not detect rake tasks (LanguagePack::Helpers::RakeRunner::CannotLoadRakefileError)

### ISSUE THREAD

**Issue by escanxr** [heroku/heroku-buildpack-ruby#1127]
Hi,

I am currently facing an error which I cannot resolve. I have already spent the day looking for it, and I do not know what to do.

On first deploy:

```
-----> Detecting rake tasks
remote: /tmp/buildpackBnpNg/lib/language_pack/helpers/rake_runner.rb:106:in `load_rake_tasks!': Could not detect rake tasks (LanguagePack::Helpers::RakeRunner::CannotLoadRakefileError)
remote: ensure you can run `$ bundle exec rake -P` against your app
remote: and using the production group of your Gemfile.
remote: rake aborted!
remote: NoMethodError: undefined method `[]' for nil:NilClass
remote: /tmp/build/config/application.rb:14:in `<class:Application>'
remote: /tmp/build/config/application.rb:9:in `<module:Whatsupgenius>'
remote: /tmp/build/config/application.rb:8:in `<top (required)>'
remote: /tmp/build/Rakefile:7:in `require_relative'
remote: /tmp/build/Rakefile:7:in `<top (required)>'
remote: /tmp/build/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/rake_module.rb:29:in `load'
remote: /tmp/build/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/rake_module.rb:29:in `load_rakefile'
remote: /tmp/build/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:703:in `raw_load_rakefile'
remote: /tmp/build/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:104:in `block in load_rakefile'
remote: /tmp/build/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
remote: /tmp/build/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:103:in `load_rakefile'
remote: /tmp/build/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:82:in `block in run'
remote: /tmp/build/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
remote: /tmp/build/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:80:in `run'
remote: /tmp/build/bin/rake:6:in `<main>'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/ruby.rb:1030:in `rake'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/rails2.rb:85:in `has_jobs_work_task?'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/rails2.rb:53:in `block in default_process_types'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/instrument.rb:17:in `block in instrument'
remote: 	from /tmp/tmp.mcyWBuV2Rg/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/instrument.rb:16:in `instrument'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/base.rb:50:in `instrument'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/base.rb:46:in `instrument'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/rails2.rb:46:in `default_process_types'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/rails3.rb:29:in `block in default_process_types'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/instrument.rb:17:in `block in instrument'
remote: 	from /tmp/tmp.mcyWBuV2Rg/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/instrument.rb:16:in `instrument'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/base.rb:50:in `instrument'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/base.rb:46:in `instrument'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/rails3.rb:23:in `default_process_types'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/rails4.rb:26:in `block in default_process_types'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/instrument.rb:17:in `block in instrument'
remote: 	from /tmp/tmp.mcyWBuV2Rg/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/instrument.rb:16:in `instrument'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/base.rb:50:in `instrument'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/base.rb:46:in `instrument'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/rails4.rb:25:in `default_process_types'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/base.rb:126:in `build_release'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/base.rb:155:in `write_release_yaml'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/base.rb:84:in `compile'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/ruby.rb:120:in `block in compile'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/instrument.rb:17:in `block in instrument'
remote: 	from /tmp/tmp.mcyWBuV2Rg/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/instrument.rb:16:in `instrument'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/base.rb:50:in `instrument'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/base.rb:46:in `instrument'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/ruby.rb:91:in `compile'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/rails2.rb:62:in `block in compile'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/instrument.rb:17:in `block in instrument'
remote: 	from /tmp/tmp.mcyWBuV2Rg/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/instrument.rb:16:in `instrument'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/base.rb:50:in `instrument'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/base.rb:46:in `instrument'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/rails2.rb:60:in `compile'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/rails3.rb:42:in `block in compile'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/instrument.rb:17:in `block in instrument'
remote: 	from /tmp/tmp.mcyWBuV2Rg/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/instrument.rb:16:in `instrument'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/base.rb:50:in `instrument'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/base.rb:46:in `instrument'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/rails3.rb:41:in `compile'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/rails4.rb:35:in `block in compile'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/instrument.rb:17:in `block in instrument'
remote: 	from /tmp/tmp.mcyWBuV2Rg/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/instrument.rb:16:in `instrument'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/base.rb:50:in `instrument'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/base.rb:46:in `instrument'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/rails4.rb:34:in `compile'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/rails6.rb:20:in `block in compile'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/instrument.rb:17:in `block in instrument'
remote: 	from /tmp/tmp.mcyWBuV2Rg/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/instrument.rb:16:in `instrument'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/base.rb:50:in `instrument'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/base.rb:46:in `instrument'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/rails6.rb:18:in `compile'
remote: 	from /tmp/buildpackBnpNg/bin/support/ruby_compile:20:in `block (2 levels) in <main>'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/base.rb:190:in `log'
remote: 	from /tmp/buildpackBnpNg/bin/support/ruby_compile:19:in `block in <main>'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/instrument.rb:35:in `block in trace'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/instrument.rb:17:in `block in instrument'
remote: 	from /tmp/tmp.mcyWBuV2Rg/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/instrument.rb:16:in `instrument'
remote: 	from /tmp/buildpackBnpNg/lib/language_pack/instrument.rb:35:in `trace'
remote: 	from /tmp/buildpackBnpNg/bin/support/ruby_compile:15:in `<main>'

       !
       !     Could not detect rake tasks
       !     ensure you can run `$ bundle exec rake -P` against your app
       !     and using the production group of your Gemfile.
       !     rake aborted!
       !     NoMethodError: undefined method `[]' for nil:NilClass
       !     /tmp/build/config/application.rb:14:in `<class:Application>'
       !     /tmp/build/config/application.rb:9:in `<module:Whatsupgenius>'
       !     /tmp/build/config/application.rb:8:in `<top (required)>'
       !     /tmp/build/Rakefile:7:in `require_relative'
       !     /tmp/build/Rakefile:7:in `<top (required)>'
       !     /tmp/build/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/rake_module.rb:29:in `load'
       !     /tmp/build/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/rake_module.rb:29:in `load_rakefile'
       !     /tmp/build/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:703:in `raw_load_rakefile'
       !     /tmp/build/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:104:in `block in load_rakefile'
       !     /tmp/build/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
       !     /tmp/build/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:103:in `load_rakefile'
       !     /tmp/build/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:82:in `block in run'
       !     /tmp/build/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
       !     /tmp/build/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:80:in `run'
       !     /tmp/build/bin/rake:6:in `<main>'
       !
```

The `bundle exec rake -P` works locally.

My stack:
  – Bundler version 2.2.11
  – Ruby 3.0.0
  – Rails 6.1.3

I'm using the latest buildpack.

Any idea? Your help would be really appreciated!

**Comment by schneems** [comment]
Can you open up a support ticket so I can get access to your application. You can post back a link to the ticket on this thread.

This error is coming from your app:

```
remote: NoMethodError: undefined method `[]' for nil:NilClass
remote: /tmp/build/config/application.rb:14:in `<class:Application>'
remote: /tmp/build/config/application.rb:9:in `<module:Whatsupgenius>'
remote: /tmp/build/config/application.rb:8:in `<top (required)>
```

You'll need to see what's on line 14 of application.rb to know what it's calling [] on and why its nil in production.


The bundle exec rake -P works locally.

Try with:

```
RAILS_ENV=production bundle exec rake -P
```

**Comment by escanxr** [comment]
Thanks for your answer @schneems.
Since I couldn't see what was wrong with line 14, I thought the problem was somewhere else. But you were right, after digging longer thanks to your recommendations, it was a credentials problem. I had to regenerate the master.key and credentials.yml.enc files.

I close the issue, thank you again!
