### ISSUE TITLE
Build failing after bumping mini_racer gem version

### ISSUE THREAD

**Issue by texpert** [heroku/heroku-buildpack-ruby#1147]
Log of the failed build:

```bash
10:28 $ git push heroku
Enumerating objects: 24, done.
Counting objects: 100% (24/24), done.
Delta compression using up to 16 threads
Compressing objects: 100% (21/21), done.
Writing objects: 100% (21/21), 5.68 KiB | 5.68 MiB/s, done.
Total 21 (delta 13), reused 0 (delta 0), pack-reused 0
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Building on the Heroku-18 stack
remote: -----> Using buildpack: heroku/ruby
remote: -----> Ruby app detected
remote: -----> Installing bundler 2.2.11
remote: -----> Removing BUNDLED WITH version in the Gemfile.lock
remote: -----> Compiling Ruby/Rails
remote: -----> Using Ruby version: ruby-2.6.6
remote: -----> Installing dependencies using bundler 2.2.11
remote:        Running: BUNDLE_WITHOUT='development:test' BUNDLE_PATH=vendor/bundle BUNDLE_BIN=vendor/bundle/bin BUNDLE_DEPLOYMENT=1 bundle install -j4
remote:        Fetching gem metadata from https://rubygems.org/..........
remote:        Using rake 13.0.3
remote:        Using concurrent-ruby 1.1.8
remote:        Using minitest 5.14.4
remote:        Using zeitwerk 2.4.2
remote:        Using builder 3.2.4
remote:        Using erubi 1.10.0
remote:        Using mini_portile2 2.5.0
remote:        Using racc 1.5.2
remote:        Using crass 1.0.6
remote:        Using rack 2.2.3
remote:        Using nio4r 2.5.7
remote:        Using websocket-extensions 0.1.5
remote:        Using marcel 1.0.1
remote:        Using mini_mime 1.0.3
remote:        Using aws-eventstream 1.1.1
remote:        Fetching aws-partitions 1.443.0
remote:        Using jmespath 1.4.0
remote:        Using bcrypt 3.1.16
remote:        Using msgpack 1.4.2
remote:        Using method_source 1.0.0
remote:        Using thor 1.1.0
remote:        Using bundler 2.2.11
remote:        Using json 2.5.1
remote:        Using cancancan 3.2.1
remote:        Using coffee-script-source 1.12.2
remote:        Using execjs 2.7.0
remote:        Using mini_magick 4.11.0
remote:        Using ffi 1.15.0
remote:        Using tilt 2.0.10
remote:        Using will_paginate 3.3.0
remote:        Fetching libv8-node 15.14.0.0 (x86_64-linux-musl)
remote:        Using pg 1.2.3
remote:        Using turbolinks-source 5.2.0
remote:        Using i18n 1.8.10
remote:        Using tzinfo 2.0.4
remote:        Using nokogiri 1.11.3 (x86_64-linux)
remote:        Using websocket-driver 0.7.3
remote:        Using mail 2.7.1
remote:        Using aws-sigv4 1.2.3
remote:        Using puma 5.2.2
remote:        Using rack-test 1.1.0
remote:        Using sprockets 4.0.2
remote:        Using request_store 1.5.0
remote:        Using bootsnap 1.7.3
remote:        Using recaptcha 5.7.0
remote:        Using coffee-script 2.4.1
remote:        Using sassc 2.4.0
remote:        Using will_paginate-bootstrap 1.0.2
remote:        Using uglifier 4.2.0
remote:        Using activesupport 6.1.3.1
remote:        Using loofah 2.9.1
remote:        Using non-digest-assets 1.0.10
remote:        Using turbolinks 5.2.1
remote:        Using rails-dom-testing 2.0.3
remote:        Using rails-html-sanitizer 1.3.0
remote:        Using globalid 0.4.2
remote:        Using activemodel 6.1.3.1
remote:        Using jbuilder 2.11.2
remote:        Using activejob 6.1.3.1
remote:        Using actionview 6.1.3.1
remote:        Using activerecord 6.1.3.1
remote:        Using activemodel-serializers-xml 1.0.2
remote:        Using actionpack 6.1.3.1
remote:        Using actioncable 6.1.3.1
remote:        Using activestorage 6.1.3.1
remote:        Using actionmailer 6.1.3.1
remote:        Using railties 6.1.3.1
remote:        Using sprockets-rails 3.2.2
remote:        Using draper 4.0.1
remote:        Using meta-tags 2.14.0
remote:        Using actionmailbox 6.1.3.1
remote:        Using actiontext 6.1.3.1
remote:        Fetching breadcrumbs_on_rails 4.1.0
remote:        Using coffee-rails 5.0.0
remote:        Using font-awesome-rails 4.7.0.7
remote:        Using jquery-rails 4.4.0
remote:        Using sassc-rails 2.1.2
remote:        Installing aws-partitions 1.443.0
remote:        Using tinymce-rails 4.9.11
remote:        Using rails 6.1.3.1
remote:        Using sass-rails 6.0.0
remote:        Using cama_contact_form 0.0.30
remote:        Using cama_meta_tag 1.7
remote:        Using aws-sdk-core 3.113.1
remote:        Using aws-sdk-kms 1.43.0
remote:        Using aws-sdk-s3 1.93.0
remote:        Installing breadcrumbs_on_rails 4.1.0
remote:        Using camaleon_cms 2.6.0
remote:        Installing libv8-node 15.14.0.0 (x86_64-linux-musl)
remote:        Fetching mini_racer 0.4.0
remote:        Installing mini_racer 0.4.0 with native extensions
remote:        Bundle complete! 24 Gemfile dependencies, 87 gems now installed.
remote:        Gems in the groups development and test were not installed.
remote:        Bundled gems are installed into `./vendor/bundle`
remote:        Removing libv8-8.4.255.0-x86_64 (linux)
remote:        Removing aws-partitions (1.442.0)
remote:        Removing mini_racer (0.3.1)
remote:        Removing breadcrumbs_on_rails (4.0.0)
remote:        Bundle completed (18.31s)
remote:        Cleaning up the bundler cache.
remote: -----> Installing node-v12.16.2-linux-x64
remote: -----> Detecting rake tasks
remote: 
remote:  !
remote:  !     Could not detect rake tasks
remote:  !     ensure you can run `$ bundle exec rake -P` against your app
remote:  !     and using the production group of your Gemfile.
remote:  !     /tmp/build_c8909d89/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.11/lib/bundler/spec_set.rb:88:in `block in materialize': Could not find libv8-node-15.14.0.0 in any of the sources (Bundler::GemNotFound)
remote:  !     from /tmp/build_c8909d89/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.11/lib/bundler/spec_set.rb:82:in `map!'
remote:  !     from /tmp/build_c8909d89/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.11/lib/bundler/spec_set.rb:82:in `materialize'
remote:  !     from /tmp/build_c8909d89/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.11/lib/bundler/definition.rb:170:in `specs'
remote:  !     from /tmp/build_c8909d89/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.11/lib/bundler/definition.rb:240:in `specs_for'
remote:  !     from /tmp/build_c8909d89/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.11/lib/bundler/definition.rb:222:in `requested_specs'
remote:  !     from /tmp/build_c8909d89/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.11/lib/bundler/runtime.rb:91:in `block in definition_method'
remote:  !     from /tmp/build_c8909d89/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.11/lib/bundler/runtime.rb:20:in `setup'
remote:  !     from /tmp/build_c8909d89/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.11/lib/bundler.rb:148:in `setup'
remote:  !     from /tmp/build_c8909d89/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.11/lib/bundler/setup.rb:20:in `block in <top (required)>'
remote:  !     from /tmp/build_c8909d89/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.11/lib/bundler/ui/shell.rb:136:in `with_level'
remote:  !     from /tmp/build_c8909d89/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.11/lib/bundler/ui/shell.rb:88:in `silence'
remote:  !     from /tmp/build_c8909d89/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.11/lib/bundler/setup.rb:20:in `<top (required)>'
remote:  !     from /tmp/build_c8909d89/vendor/ruby-2.6.6/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
remote:  !     from /tmp/build_c8909d89/vendor/ruby-2.6.6/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
remote:  !     from /tmp/build_c8909d89/config/boot.rb:5:in `<top (required)>'
remote:  !     from /tmp/build_c8909d89/bin/rake:3:in `require_relative'
remote:  !     from /tmp/build_c8909d89/bin/rake:3:in `<main>'
remote:  !
remote: /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/helpers/rake_runner.rb:106:in `load_rake_tasks!': Could not detect rake tasks (LanguagePack::Helpers::RakeRunner::CannotLoadRakefileError)
remote: ensure you can run `$ bundle exec rake -P` against your app
remote: and using the production group of your Gemfile.
remote: /tmp/build_c8909d89/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.11/lib/bundler/spec_set.rb:88:in `block in materialize': Could not find libv8-node-15.14.0.0 in any of the sources (Bundler::GemNotFound)
remote: 	from /tmp/build_c8909d89/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.11/lib/bundler/spec_set.rb:82:in `map!'
remote: 	from /tmp/build_c8909d89/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.11/lib/bundler/spec_set.rb:82:in `materialize'
remote: 	from /tmp/build_c8909d89/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.11/lib/bundler/definition.rb:170:in `specs'
remote: 	from /tmp/build_c8909d89/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.11/lib/bundler/definition.rb:240:in `specs_for'
remote: 	from /tmp/build_c8909d89/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.11/lib/bundler/definition.rb:222:in `requested_specs'
remote: 	from /tmp/build_c8909d89/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.11/lib/bundler/runtime.rb:91:in `block in definition_method'
remote: 	from /tmp/build_c8909d89/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.11/lib/bundler/runtime.rb:20:in `setup'
remote: 	from /tmp/build_c8909d89/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.11/lib/bundler.rb:148:in `setup'
remote: 	from /tmp/build_c8909d89/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.11/lib/bundler/setup.rb:20:in `block in <top (required)>'
remote: 	from /tmp/build_c8909d89/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.11/lib/bundler/ui/shell.rb:136:in `with_level'
remote: 	from /tmp/build_c8909d89/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.11/lib/bundler/ui/shell.rb:88:in `silence'
remote: 	from /tmp/build_c8909d89/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.11/lib/bundler/setup.rb:20:in `<top (required)>'
remote: 	from /tmp/build_c8909d89/vendor/ruby-2.6.6/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
remote: 	from /tmp/build_c8909d89/vendor/ruby-2.6.6/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
remote: 	from /tmp/build_c8909d89/config/boot.rb:5:in `<top (required)>'
remote: 	from /tmp/build_c8909d89/bin/rake:3:in `require_relative'
remote: 	from /tmp/build_c8909d89/bin/rake:3:in `<main>'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:1030:in `rake'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails4.rb:78:in `block (2 levels) in run_assets_precompile_rake_task'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:190:in `log'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails4.rb:72:in `block in run_assets_precompile_rake_task'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:17:in `block in instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/vendor/ruby/heroku-18/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:16:in `instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:50:in `instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:46:in `instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails4.rb:71:in `run_assets_precompile_rake_task'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:112:in `block (2 levels) in compile'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:1051:in `allow_git'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:105:in `block in compile'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:17:in `block in instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/vendor/ruby/heroku-18/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:16:in `instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:50:in `instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:46:in `instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:91:in `compile'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails2.rb:62:in `block in compile'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:17:in `block in instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/vendor/ruby/heroku-18/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:16:in `instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:50:in `instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:46:in `instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails2.rb:60:in `compile'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails3.rb:42:in `block in compile'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:17:in `block in instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/vendor/ruby/heroku-18/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:16:in `instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:50:in `instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:46:in `instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails3.rb:41:in `compile'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails4.rb:35:in `block in compile'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:17:in `block in instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/vendor/ruby/heroku-18/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:16:in `instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:50:in `instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:46:in `instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails4.rb:34:in `compile'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails6.rb:20:in `block in compile'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:17:in `block in instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/vendor/ruby/heroku-18/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:16:in `instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:50:in `instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:46:in `instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails6.rb:18:in `compile'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/bin/support/ruby_compile:20:in `block (2 levels) in <main>'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:190:in `log'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/bin/support/ruby_compile:19:in `block in <main>'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:35:in `block in trace'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:17:in `block in instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/vendor/ruby/heroku-18/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:16:in `instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:35:in `trace'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/bin/support/ruby_compile:15:in `<main>'
remote:  !     Push rejected, failed to compile Ruby app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to florsan.
remote: 
To https://git.heroku.com/florsan.git
 ! [remote rejected] main -> main (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/florsan.git'
```

I wonder why the build is `Installing libv8-node 15.14.0.0 (x86_64-linux-musl)` on a Ubuntu-18 stack?

( the suggested `ensure you can run `$ bundle exec rake -P` against your app` is working OK with RAILS_ENV=production.

**Comment by schneems** [comment]
This is your issue:

```
remote:  !     /tmp/build_c8909d89/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.11/lib/bundler/spec_set.rb:88:in `block in materialize': Could not find libv8-node-15.14.0.0 in any of the sources (Bundler::GemNotFound)
```

The version of mini_racer is looking for libv8-node-15.14.0.0 but your app is using a different node version: 

```
remote: -----> Installing node-v12.16.2-linux-x64
```

You can specify a node version using the `heroku/nodejs` buildpack and adding a `package.json` file https://devcenter.heroku.com/articles/ruby-support#installed-binaries. 

If you've got an app specific question, please open a ticket on Heroku's support tracker and you'll get a response faster. I don't always check the issue tracker every day. I also prefer to keep issues on github for buildpack specific bugs. If you're not sure if it's a bug in the buildpack or your app, it's best to go through a heroku ticket.

**Comment by texpert** [comment]
@schneems , thanks for advise, but adding the `heroku/nodejs` buildpack didn't help. Still `Could not find libv8-node-15.14.0.0 in any of the sources`, though now `remote:        Downloading and installing node 15.14.0...`.

Anyway, thanks - I have opened a ticket st Heroku support.

**Comment by texpert** [comment]
The issue was solved after adding linux platform to Gemfile.lock explicitly:

```bash
bundle lock --add-platform x86_64-linux
```

@schneems , thanks again for great help!

**Comment by nightpool** [comment]
I wasn't able to resolve this issue after running `bundle lock --add-platform x86_64-linux`:

```
remote:        ensure you can run `$ bundle exec rake -P` against your app
remote:        and using the production group of your Gemfile.
remote:        /tmp/build_675cf94d/vendor/bundle/ruby/2.5.0/gems/bundler-1.17.3/lib/bundler/spec_set.rb:91:in `block in materialize': Could not find libv8-node-15.14.0.1-x86_64-linux in any of the sources (Bundler::GemNotFound)
remote:        	from /tmp/build_675cf94d/vendor/bundle/ruby/2.5.0/gems/bundler-1.17.3/lib/bundler/spec_set.rb:85:in `map!'
remote:        	from /tmp/build_675cf94d/vendor/bundle/ruby/2.5.0/gems/bundler-1.17.3/lib/bundler/spec_set.rb:85:in `materialize'
remote:        	from /tmp/build_675cf94d/vendor/bundle/ruby/2.5.0/gems/bundler-1.17.3/lib/bundler/definition.rb:170:in `specs'
remote:        	from /tmp/build_675cf94d/vendor/bundle/ruby/2.5.0/gems/bundler-1.17.3/lib/bundler/definition.rb:237:in `specs_for'
remote:        	from /tmp/build_675cf94d/vendor/bundle/ruby/2.5.0/gems/bundler-1.17.3/lib/bundler/definition.rb:226:in `requested_specs'
remote:        	from /tmp/build_675cf94d/vendor/bundle/ruby/2.5.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:108:in `block in definition_method'
remote:        	from /tmp/build_675cf94d/vendor/bundle/ruby/2.5.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:20:in `setup'
remote:        	from /tmp/build_675cf94d/vendor/bundle/ruby/2.5.0/gems/bundler-1.17.3/lib/bundler.rb:107:in `setup'
remote:        	from /tmp/build_675cf94d/vendor/bundle/ruby/2.5.0/gems/bundler-1.17.3/lib/bundler/setup.rb:20:in `<top (required)>'
remote:        	from /tmp/build_675cf94d/vendor/ruby-2.5.8/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
remote:        	from /tmp/build_675cf94d/vendor/ruby-2.5.8/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
remote:        	from /tmp/build_675cf94d/vendor/bundle/bin/rake:27:in `<main>'
```

to @schneems earlier point, node and libv8-node are completely unrelated, libv8-node is a precompiled binary that's *based* on the node source, but doesn't require node in any way.

**Comment by nightpool** [comment]
@robbyrussell Yes, we ended up using this patch to enable `libv8` on bundler 1: https://github.com/Genius/heroku-buildpack-ruby/commit/50ac7aa7510867362ce793174d62b65dace6ab1f

For your own servers, setting BUNDLE_SPECIFIC_PLATFORM=1 in the environment / bundler config seems like the way to go.

**Comment by brandoncc** [comment]
If anyone else ends up here and spends countless hours trying every solution they find.... try `bundle update --bundler`. Bundler 1 was the entire problem for me, and bundler 2 works great!

**Comment by hisapy** [comment]
Hi everyone, what worked for me on Heroku, besides `bundle lock --add-platform x86_64-linux` was adding `BUNDLE_SPECIFIC_PLATFORM` with the value `true` in the Config Vars section on my app's settings, e.g., `https://dashboard.heroku.com/apps/your-app/settings`

**Comment by hisapy** [comment]
Yes, I'm using bundler 1.17.3 for a small legacy app and can't upgrade for the moment.
