### ISSUE TITLE
Could not detect rake tasks

### ISSUE THREAD

**Issue by collimarco** [heroku/heroku-buildpack-ruby#1232]
Create a new Rails app (v6.1.4) and then run:

```
pack build example:abc --builder heroku/buildpacks:20
```

I get this error:

```
-----> Detecting rake tasks

 !
 !     Could not detect rake tasks
 !     ensure you can run `$ bundle exec rake -P` against your app
 !     and using the production group of your Gemfile.
 !     rake aborted!
 !     URI::InvalidURIError: bad URI(is not URI?): ://user:pass@127.0.0.1/dbname
 !     /layers/heroku_ruby/ruby/vendor/ruby-3.0.2/lib/ruby/3.0.0/uri/rfc2396_parser.rb:176:in `split'
 !     /layers/heroku_ruby/ruby/vendor/ruby-3.0.2/lib/ruby/3.0.0/uri/rfc2396_parser.rb:210:in `parse'
 !     /layers/heroku_ruby/gems/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.4.1/lib/active_record/database_configurations/connection_url_resolver.rb:25:in `initialize'
 !     /layers/heroku_ruby/gems/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.4.1/lib/active_record/database_configurations/url_config.rb:48:in `new'
...
```

I tried to run `$ RAILS_ENV=production bundle exec rake -P` and it works properly... so this seems a bug in the buildpack. 

Any idea?

**Comment by collimarco** [comment]
Although the error message is misleading, I was able to fix by installing the `pg` gem and using a new `database.yml`.
