### ISSUE TITLE
Heroku-22 fails installing gems

### ISSUE THREAD

**Issue by carlosbalsas** [heroku/heroku-buildpack-ruby#1361]
Logs:

> -----> Building on the Heroku-22 stack
-----> Using buildpacks:
       1. heroku/nodejs
       2. heroku/ruby
       3. heroku-community/awscli
       4. heroku-community/cli
       5. heroku/metrics
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       USE_YARN_CACHE=true
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       
-----> Installing binaries
       engines.node (package.json):  14.x
       engines.npm (package.json):   unspecified (use default)
       engines.yarn (package.json):  1.x
       
       Resolving node version 14.x...
       Downloading and installing node 14.21.2...
       Using default npm version: 6.14.17
       Resolving yarn version 1.x...
       Downloading and installing yarn (1.22.19)
       Installed yarn 1.22.19
       
-----> Installing dependencies
       Installing node modules (yarn.lock)
       yarn install v1.22.19
       warning package.json: No license field
       warning No license field
       [1/4] Resolving packages...
       [2/4] Fetching packages...
       [3/4] Linking dependencies...
       warning " > styled-components@5.3.3" has unmet peer dependency "react-is@>= 16.8.0".
       warning "@dokspot/table-component > react-scripts > @typescript-eslint/eslint-plugin > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
       warning " > html-react-parser@0.10.5" has incorrect peer dependency "react@^0.14 || ^15 || ^16".
       warning " > react-bootstrap-table-next@3.3.5" has incorrect peer dependency "react@^16.3.0".
       warning " > react-bootstrap-table-next@3.3.5" has incorrect peer dependency "react-dom@^16.3.0".
       warning " > react-bootstrap-table2-filter@1.3.3" has incorrect peer dependency "react@^16.3.0".
       warning " > react-bootstrap-table2-filter@1.3.3" has incorrect peer dependency "react-dom@^16.3.0".
       warning " > react-bootstrap-table2-paginator@2.1.2" has incorrect peer dependency "react@^16.3.0".
       warning " > react-bootstrap-table2-paginator@2.1.2" has incorrect peer dependency "react-dom@^16.3.0".
       warning " > react-bootstrap-table2-toolkit@2.1.3" has incorrect peer dependency "react@^16.3.0".
       warning " > react-bootstrap-table2-toolkit@2.1.3" has incorrect peer dependency "react-dom@^16.3.0".
       warning " > react-bootstrap-typeahead@3.4.7" has incorrect peer dependency "react@^0.14.0 || ^15.2.0 || ^16.0.0".
       warning " > react-bootstrap-typeahead@3.4.7" has incorrect peer dependency "react-dom@^0.14.0 || ^15.2.0 || ^16.0.0".
       warning "react-bootstrap-typeahead > create-react-context@0.3.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
       warning " > react-flags@0.1.18" has incorrect peer dependency "react@0.13 - 16.x".
       warning "react-helmet > react-side-effect@1.2.0" has incorrect peer dependency "react@^0.13.0 || ^0.14.0 || ^15.0.0 || ^16.0.0".
       warning " > react-html-parser@2.0.2" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0-0".
       warning " > react-pdf@4.2.0" has incorrect peer dependency "react@^16.3.0".
       warning " > react-pdf@4.2.0" has incorrect peer dependency "react-dom@^16.3.0".
       warning " > react-sizeme@2.6.12" has incorrect peer dependency "react@^0.14.0 || ^15.0.0-0 || ^16.0.0".
       warning " > react-sizeme@2.6.12" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0-0 || ^16.0.0".
       warning " > react-summernote@2.0.2" has incorrect peer dependency "bootstrap@^3.3.6".
       warning " > react-summernote@2.0.2" has incorrect peer dependency "react@^15.0.0".
       warning " > react-tagsinput@3.19.0" has incorrect peer dependency "react@^16.0.0 || ^15.0.0 || ^0.14.0".
       warning " > recompose@0.30.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
       warning " > react-test-renderer@16.14.0" has incorrect peer dependency "react@^16.14.0".
       [4/4] Building fresh packages...
       Done in 218.24s.
       
-----> Build
       
-----> Pruning devDependencies
       yarn install v1.22.19
       warning package.json: No license field
       warning No license field
       [1/4] Resolving packages...
       [2/4] Fetching packages...
       [3/4] Linking dependencies...
       warning " > styled-components@5.3.3" has unmet peer dependency "react-is@>= 16.8.0".
       warning "@dokspot/table-component > react-scripts > @typescript-eslint/eslint-plugin > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
       warning " > html-react-parser@0.10.5" has incorrect peer dependency "react@^0.14 || ^15 || ^16".
       warning " > react-bootstrap-table-next@3.3.5" has incorrect peer dependency "react@^16.3.0".
       warning " > react-bootstrap-table-next@3.3.5" has incorrect peer dependency "react-dom@^16.3.0".
       warning " > react-bootstrap-table2-filter@1.3.3" has incorrect peer dependency "react@^16.3.0".
       warning " > react-bootstrap-table2-filter@1.3.3" has incorrect peer dependency "react-dom@^16.3.0".
       warning " > react-bootstrap-table2-paginator@2.1.2" has incorrect peer dependency "react@^16.3.0".
       warning " > react-bootstrap-table2-paginator@2.1.2" has incorrect peer dependency "react-dom@^16.3.0".
       warning " > react-bootstrap-table2-toolkit@2.1.3" has incorrect peer dependency "react@^16.3.0".
       warning " > react-bootstrap-table2-toolkit@2.1.3" has incorrect peer dependency "react-dom@^16.3.0".
       warning " > react-bootstrap-typeahead@3.4.7" has incorrect peer dependency "react@^0.14.0 || ^15.2.0 || ^16.0.0".
       warning " > react-bootstrap-typeahead@3.4.7" has incorrect peer dependency "react-dom@^0.14.0 || ^15.2.0 || ^16.0.0".
       warning "react-bootstrap-typeahead > create-react-context@0.3.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
       warning " > react-flags@0.1.18" has incorrect peer dependency "react@0.13 - 16.x".
       warning "react-helmet > react-side-effect@1.2.0" has incorrect peer dependency "react@^0.13.0 || ^0.14.0 || ^15.0.0 || ^16.0.0".
       warning " > react-html-parser@2.0.2" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0-0".
       warning " > react-pdf@4.2.0" has incorrect peer dependency "react@^16.3.0".
       warning " > react-pdf@4.2.0" has incorrect peer dependency "react-dom@^16.3.0".
       warning " > react-sizeme@2.6.12" has incorrect peer dependency "react@^0.14.0 || ^15.0.0-0 || ^16.0.0".
       warning " > react-sizeme@2.6.12" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0-0 || ^16.0.0".
       warning " > react-summernote@2.0.2" has incorrect peer dependency "bootstrap@^3.3.6".
       warning " > react-summernote@2.0.2" has incorrect peer dependency "react@^15.0.0".
       warning " > react-tagsinput@3.19.0" has incorrect peer dependency "react@^16.0.0 || ^15.0.0 || ^0.14.0".
       warning " > recompose@0.30.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
       warning " > react-test-renderer@16.14.0" has incorrect peer dependency "react@^16.14.0".
       [4/4] Building fresh packages...
       warning Ignored scripts due to flag.
       Done in 17.40s.
       
-----> Caching build
       - yarn cache
       
-----> Build succeeded!
 !     Unmet dependencies don't fail yarn install but may cause runtime issues
       https://github.com/npm/npm/issues/7494
-----> Ruby app detected
-----> Installing bundler 2.3.25
-----> Removing BUNDLED WITH version in the Gemfile.lock
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-3.1.0
-----> Installing dependencies using bundler 2.3.25
       Running: BUNDLE_WITHOUT='development:test' BUNDLE_PATH=vendor/bundle BUNDLE_BIN=vendor/bundle/bin BUNDLE_DEPLOYMENT=1 bundle install -j4
       Bundle completed (0.03s)
       Cleaning up the bundler cache.
-----> Detecting rake tasks
 !
 !     Could not detect rake tasks
 !     ensure you can run `$ bundle exec rake -P` against your app
 !     and using the production group of your Gemfile.
 !     fatal: not a git repository (or any parent up to mount point /)
 !     Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
 !     /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/source/git.rb:214:in `rescue in load_spec_files': https://github.com/redis-store/redis-rails.git (at master@e5ca108) is not yet checked out. Run `bundle install` first. (Bundler::GitError)
 !     from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/source/git.rb:210:in `load_spec_files'
 !     from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/source/path.rb:107:in `local_specs'
 !     from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/source/git.rb:178:in `specs'
 !     from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/lazy_specification.rb:82:in `materialize_for_installation'
 !     from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/spec_set.rb:194:in `block in specs_for_dependency'
 !     from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/spec_set.rb:194:in `map'
 !     from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/spec_set.rb:194:in `specs_for_dependency'
 !     from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/spec_set.rb:33:in `block in for'
 !     from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/spec_set.rb:22:in `loop'
 !     from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/spec_set.rb:22:in `for'
 !     from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/spec_set.rb:79:in `materialize'
 !     from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/definition.rb:490:in `materialize'
 !     from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/definition.rb:187:in `specs'
 !     from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/definition.rb:244:in `specs_for'
 !     from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/runtime.rb:18:in `setup'
 !     from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler.rb:161:in `setup'
 !     from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/setup.rb:20:in `block in <top (required)>'
 !     from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/ui/shell.rb:136:in `with_level'
 !     from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/ui/shell.rb:88:in `silence'
 !     from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/setup.rb:20:in `<top (required)>'
 !     from <internal:/tmp/build_dc5b8ce1/vendor/ruby-3.1.0/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
 !     from <internal:/tmp/build_dc5b8ce1/vendor/ruby-3.1.0/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
 !     from /tmp/build_dc5b8ce1/config/boot.rb:3:in `<top (required)>'
 !     from /tmp/build_dc5b8ce1/bin/rake:3:in `require_relative'
 !     from /tmp/build_dc5b8ce1/bin/rake:3:in `<main>'
 !     /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/source/path.rb:209:in `load_spec_files': The path `/tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/bundler/gems/redis-rails-e5ca10851c83` does not exist. (Bundler::PathError)
 !     from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/source/git.rb:211:in `load_spec_files'
 !     from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/source/path.rb:107:in `local_specs'
 !     from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/source/git.rb:178:in `specs'
 !     from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/lazy_specification.rb:82:in `materialize_for_installation'
 !     from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/spec_set.rb:194:in `block in specs_for_dependency'
 !     from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/spec_set.rb:194:in `map'
 !     from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/spec_set.rb:194:in `specs_for_dependency'
 !     from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/spec_set.rb:33:in `block in for'
 !     from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/spec_set.rb:22:in `loop'
 !     from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/spec_set.rb:22:in `for'
 !     from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/spec_set.rb:79:in `materialize'
 !     from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/definition.rb:490:in `materialize'
 !     from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/definition.rb:187:in `specs'
 !     from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/definition.rb:244:in `specs_for'
 !     from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/runtime.rb:18:in `setup'
 !     from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler.rb:161:in `setup'
 !     from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/setup.rb:20:in `block in <top (required)>'
 !     from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/ui/shell.rb:136:in `with_level'
 !     from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/ui/shell.rb:88:in `silence'
 !     from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/setup.rb:20:in `<top (required)>'
 !     from <internal:/tmp/build_dc5b8ce1/vendor/ruby-3.1.0/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
 !     from <internal:/tmp/build_dc5b8ce1/vendor/ruby-3.1.0/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
 !     from /tmp/build_dc5b8ce1/config/boot.rb:3:in `<top (required)>'
 !     from /tmp/build_dc5b8ce1/bin/rake:3:in `require_relative'
 !     from /tmp/build_dc5b8ce1/bin/rake:3:in `<main>'
 !
/tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/helpers/rake_runner.rb:100:in `load_rake_tasks!': Could not detect rake tasks (LanguagePack::Helpers::RakeRunner::CannotLoadRakefileError)
ensure you can run `$ bundle exec rake -P` against your app
and using the production group of your Gemfile.
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
/tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/source/git.rb:214:in `rescue in load_spec_files': https://github.com/redis-store/redis-rails.git (at master@e5ca108) is not yet checked out. Run `bundle install` first. (Bundler::GitError)
	from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/source/git.rb:210:in `load_spec_files'
	from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/source/path.rb:107:in `local_specs'
	from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/source/git.rb:178:in `specs'
	from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/lazy_specification.rb:82:in `materialize_for_installation'
	from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/spec_set.rb:194:in `block in specs_for_dependency'
	from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/spec_set.rb:194:in `map'
	from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/spec_set.rb:194:in `specs_for_dependency'
	from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/spec_set.rb:33:in `block in for'
	from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/spec_set.rb:22:in `loop'
	from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/spec_set.rb:22:in `for'
	from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/spec_set.rb:79:in `materialize'
	from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/definition.rb:490:in `materialize'
	from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/definition.rb:187:in `specs'
	from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/definition.rb:244:in `specs_for'
	from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/runtime.rb:18:in `setup'
	from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler.rb:161:in `setup'
	from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/setup.rb:20:in `block in <top (required)>'
	from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/ui/shell.rb:136:in `with_level'
	from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/ui/shell.rb:88:in `silence'
	from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/setup.rb:20:in `<top (required)>'
	from <internal:/tmp/build_dc5b8ce1/vendor/ruby-3.1.0/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/tmp/build_dc5b8ce1/vendor/ruby-3.1.0/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /tmp/build_dc5b8ce1/config/boot.rb:3:in `<top (required)>'
	from /tmp/build_dc5b8ce1/bin/rake:3:in `require_relative'
	from /tmp/build_dc5b8ce1/bin/rake:3:in `<main>'
/tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/source/path.rb:209:in `load_spec_files': The path `/tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/bundler/gems/redis-rails-e5ca10851c83` does not exist. (Bundler::PathError)
	from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/source/git.rb:211:in `load_spec_files'
	from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/source/path.rb:107:in `local_specs'
	from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/source/git.rb:178:in `specs'
	from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/lazy_specification.rb:82:in `materialize_for_installation'
	from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/spec_set.rb:194:in `block in specs_for_dependency'
	from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/spec_set.rb:194:in `map'
	from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/spec_set.rb:194:in `specs_for_dependency'
	from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/spec_set.rb:33:in `block in for'
	from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/spec_set.rb:22:in `loop'
	from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/spec_set.rb:22:in `for'
	from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/spec_set.rb:79:in `materialize'
	from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/definition.rb:490:in `materialize'
	from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/definition.rb:187:in `specs'
	from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/definition.rb:244:in `specs_for'
	from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/runtime.rb:18:in `setup'
	from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler.rb:161:in `setup'
	from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/setup.rb:20:in `block in <top (required)>'
	from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/ui/shell.rb:136:in `with_level'
	from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/ui/shell.rb:88:in `silence'
	from /tmp/build_dc5b8ce1/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/setup.rb:20:in `<top (required)>'
	from <internal:/tmp/build_dc5b8ce1/vendor/ruby-3.1.0/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/tmp/build_dc5b8ce1/vendor/ruby-3.1.0/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /tmp/build_dc5b8ce1/config/boot.rb:3:in `<top (required)>'
	from /tmp/build_dc5b8ce1/bin/rake:3:in `require_relative'
	from /tmp/build_dc5b8ce1/bin/rake:3:in `<main>'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:967:in `rake'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails4.rb:69:in `block in run_assets_precompile_rake_task'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:175:in `log'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails4.rb:63:in `run_assets_precompile_rake_task'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:103:in `block in compile'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:988:in `allow_git'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:96:in `compile'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails2.rb:55:in `compile'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails3.rb:37:in `compile'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails4.rb:30:in `compile'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails6.rb:17:in `compile'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/bin/support/ruby_compile:19:in `block in <main>'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:175:in `log'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/bin/support/ruby_compile:18:in `<main>'
 !     Push rejected, failed to compile Ruby app.
 !     Push failed

Already tried: 

> $ bundle lock --add-platform ruby
$ bundle lock --add-platform x86_64-linux
$ bundle install
$ git add . ; git commit -m "Bundler fix"

**Comment by cyrillederche** [comment]
Having the same issue! Help!

**Comment by schneems** [comment]
For application specific support you'll need to go through the Heroku support channel. You didn't get a response because this isn't a monitored support channel and I was out on vacation. 

> Heroku-22 fails installing gems #1361

It looks like bundler works just fine:

```
-----> Installing dependencies using bundler 2.3.25
       Running: BUNDLE_WITHOUT='development:test' BUNDLE_PATH=vendor/bundle BUNDLE_BIN=vendor/bundle/bin BUNDLE_DEPLOYMENT=1 bundle install -j4
       Bundle completed (0.03s)
       Cleaning up the bundler cache.
```

However it's not installing ANY gems (though it's not failing either). My best guess is that you accidentally checked a file in under `vendor/bundle`. Based on the initial header of your issue I'm assuming this worked previously on another stack, but without that information I can't be sure. Here's a list of packages that changed between stacks, https://devcenter.heroku.com/articles/stack-packages. A stack upgrade would not cause gems to not be installed.

As a side note 3.1.0 is not supported, you'll need to upgrade to 3.1.3 https://devcenter.heroku.com/articles/ruby-support#supported-runtimes.

**Comment by carlosbalsas** [comment]
Solved:
I delete the content of `bin/bundle` file, accidentally.
