### ISSUE TITLE
Windows gemfile breaks deployment

### ISSUE THREAD

**Issue by jirubio** [heroku/heroku-buildpack-ruby#1472]
We started getting this error:

```
remote: =====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-ruby.git        
remote: =====> Detected Framework: Ruby        
remote: -----> Installing bundler 2.3.25        
remote: -----> Removing BUNDLED WITH version in the Gemfile.lock        
remote: -----> Compiling Ruby/Rails        
remote: -----> Using Ruby version: ruby-3.2.3        
remote: 
remote:        !        
remote:        !     undefined method `version' for nil:NilClass        
remote:        !        
remote:        !     puts "Windows `Gemfile.lock` detected, bundler #{@bundler.version} supports multiple platforms, no action taken."        
remote:        !     ^^^^^^^^        
remote:        !
remote: /tmp/buildpackuTImt/lib/language_pack/ruby.rb:698:in `block in build_bundler': undefined method `version' for nil:NilClass (NoMethodError)        
remote: 
remote:           puts "Windows `Gemfile.lock` detected, bundler #{@bundler.version} supports multiple platforms, no action taken."        
remote:                                                                    ^^^^^^^^        
remote: 	from /tmp/buildpackuTImt/lib/language_pack/base.rb:144:in `log'        
remote: 	from /tmp/buildpackuTImt/lib/language_pack/ruby.rb:683:in `build_bundler'        
remote: 	from /tmp/buildpackuTImt/lib/language_pack/ruby.rb:93:in `block in compile'        
remote: 	from /tmp/buildpackuTImt/lib/language_pack/ruby.rb:927:in `allow_git'        
remote: 	from /tmp/buildpackuTImt/lib/language_pack/ruby.rb:90:in `compile'        
remote: 	from /tmp/buildpackuTImt/lib/language_pack/rails2.rb:55:in `compile'        
remote: 	from /tmp/buildpackuTImt/lib/language_pack/rails3.rb:37:in `compile'        
remote: 	from /tmp/buildpackuTImt/lib/language_pack/rails4.rb:30:in `compile'        
remote: 	from /tmp/buildpackuTImt/lib/language_pack/rails6.rb:17:in `compile'        
remote: 	from /tmp/buildpackuTImt/bin/support/ruby_compile:19:in `block in <main>'        
remote: 	from /tmp/buildpackuTImt/lib/language_pack/base.rb:144:in `log'        
remote: 	from /tmp/buildpackuTImt/bin/support/ruby_compile:18:in `<main>'
```

Seems related to these recent changes https://github.com/heroku/heroku-buildpack-ruby/commit/03a7f545f415d46131c8bc6adb615ea256be4db5. I took a quick look at the code and maybe "@bundler.version" should be "bundler.version" instead.

**Comment by schneems** [comment]
The fix is tested and the change has been deployed https://devcenter.heroku.com/changelog-items/2912
