### ISSUE TITLE
having issues with heroku/ruby after latest yarn version bump

### ISSUE THREAD

**Issue by dzfolio** [heroku/heroku-buildpack-ruby#1516]
@schneems Update: You can manually set your node and yarn version following the docs here https://devcenter.heroku.com/articles/ruby-support-reference#node-js-support. Further, I recommend using the `heroku/ruby` buildpack and recommend against using the github url on your app.

Original report:
-----
after the newest heroku/ruby buildpack was released, we are having issues with this. what can we do?

```
remote: ###### WARNING:        
remote: 
remote:        Installing a default version (1.22.22) of Yarn        
remote:        This version is not pinned and can change over time, causing unexpected failures.        
remote:                
remote:        Heroku recommends placing the `heroku/nodejs` buildpack in front of the `heroku/ruby`        
remote:        buildpack as it offers more comprehensive Node.js support, including the ability to        
remote:        customise the Node.js version:        
remote:                
remote:        https://devcenter.heroku.com/articles/ruby-support#node-js-support        
remote: 
remote: -----> Installing node-v22.11.0-linux-x64        
remote: -----> Installing yarn-v1.22.22        
remote:         
remote:  !        
remote:  !     No such file or directory @ rb_file_s_rename - (/tmp/d20241108-1032-vggdc3/yarn-v1.22.22, yarn-v1.22.22)        
remote:  !        
remote: /tmp/tmp.l8hWafbPfJ/lib/ruby/3.1.0/fileutils.rb:541:in `rename': No such file or directory @ rb_file_s_rename - (/tmp/d20241108-1032-vggdc3/yarn-v1.22.22, yarn-v1.22.22) (Errno::ENOENT)        
remote: 	from /tmp/tmp.l8hWafbPfJ/lib/ruby/3.1.0/fileutils.rb:541:in `block in mv'        
remote: 	from /tmp/tmp.l8hWafbPfJ/lib/ruby/3.1.0/fileutils.rb:1577:in `block in fu_each_src_dest'        
remote: 	from /tmp/tmp.l8hWafbPfJ/lib/ruby/3.1.0/fileutils.rb:1593:in `fu_each_src_dest0'        
remote: 	from /tmp/tmp.l8hWafbPfJ/lib/ruby/3.1.0/fileutils.rb:1575:in `fu_each_src_dest'        
remote: 	from /tmp/tmp.l8hWafbPfJ/lib/ruby/3.1.0/fileutils.rb:532:in `mv'        
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/helpers/yarn_installer.rb:27:in `block in install'        
remote: 	from /tmp/tmp.l8hWafbPfJ/lib/ruby/3.1.0/tmpdir.rb:96:in `mktmpdir'        
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/helpers/yarn_installer.rb:22:in `install'        
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:611:in `block (2 levels) in install_binary'        
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:610:in `chdir'        
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:610:in `block in install_binary'        
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:599:in `chdir'        
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:599:in `install_binary'        
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:588:in `block in install_binaries'        
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:588:in `each'        
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:588:in `install_binaries'        
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:96:in `block in compile'        
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:930:in `allow_git'        
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:90:in `compile'        
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails2.rb:55:in `compile'        
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails3.rb:37:in `compile'        
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails4.rb:30:in `compile'        
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails6.rb:17:in `compile'        
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/bin/support/ruby_compile:19:in `block in <main>'        
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:144:in `log'        
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/bin/support/ruby_compile:18:in `<main>'        
remote:  !     Push rejected, failed to compile Ruby app.        
remote: 
remote:  !     Push failed        
```

**Comment by dzfolio** [comment]
@schneems this is breaking our ability to deploy 😢

**Comment by mlarraz** [comment]
Seems like a packaging mistake?

Previously
```bash
$ curl https://heroku-nodebin.s3.us-east-1.amazonaws.com/yarn/release/yarn-v1.22.19.tar.gz -o - | tar xzf -
```
would have a folder named `yarn-v1.22.19`

Now
```bash
curl https://heroku-nodebin.s3.us-east-1.amazonaws.com/yarn/release/yarn-v1.22.22.tar.gz -so - | tar xzf -
```
has a folder named `package`

**Comment by schneems** [comment]
Sorry about that. It seems the layout of the nodejs packaging changed in that patch release (as mentioned by @mlarraz). I rolled back the buildpack change at approx 3:00pm CST (20:00 UTC). I've indicated on the changelog that the behavior is rolled back https://devcenter.heroku.com/changelog-items/3054.

As @dzfolio recommends. I highly suggest not relying on the default node and yarn versions from the Ruby buildpack https://devcenter.heroku.com/articles/ruby-support-reference#node-js-support. This issue should be fixed, however the problem still exists on main on the buildpack. I'll keep the issue open until that happens.

**Comment by landovsky** [comment]
> @schneems this is breaking our ability to deploy 😢

I've forked the buildpack and reverted a few commits back and now it works. Feel free to use it (just replace the original buildpack to this one and back when it's fixed):
https://github.com/landovsky/heroku-buildpack-ruby

**Comment by schneems** [comment]
@landovsky I've already rolled back the change some 3 days ago. Are you still seeing failures using `heroku/ruby`? I don't recommend relying on the github url for a production application, I recommend using `heroku/ruby`.

**Comment by rodmac-fetchly** [comment]
We facing the same issue here, is there any way to manually change the yarn version?

**Comment by rodmac-fetchly** [comment]
Hoping this get merged ASAP, we have our production instance down because of this issue

**Comment by schneems** [comment]
@rodmac-fetchly I edited the issue description with mitigation instructions on how to avoid this issue entirely (use `heroku/ruby` buildpack instead of `https://github.com/heroku/heroku-buildpack-ruby`) as well as how to set your node and yarn versions manually https://devcenter.heroku.com/articles/ruby-support-reference#node-js-support.

**Comment by rodmac-fetchly** [comment]
Btw we are deploying with dokku ([https://github.com/dokku/dokku](https://github.com/dokku/dokku)) to deploy

**Comment by rodmac-fetchly** [comment]
Thanks a lot, we were able to deploy it after your fix was merged! We did try the other solution you mentionened but we weren't able to make it work. You saved the day!

**Comment by safeforge** [comment]
> Btw we are deploying with dokku (https://github.com/dokku/dokku) to deploy

It’s possible to specify a specific version of a buildpack in Dokku. I’ve resolved this by using the latest stable version, referencing it directly as follows:

```
# .buildpacks
https://github.com/heroku/heroku-buildpack-ruby.git#v281
```

FYI, this approach also works on Heroku, allowing you to lock in a specific buildpack version there too. 

Anyway, thank you @schneems for the rollback :+1:
