### ISSUE TITLE
Wrong Version of Ruby for Binstubs with CI

### ISSUE THREAD

**Issue by schneems** [heroku/heroku-buildpack-ruby#573]
When executing a CI build test runs can be started via `bin/rspec` or `bin/rails`. These have shebang lines that start like this:

```
#!/usr/bin/env ruby
```

When running on heroku CI. Ruby version is correct but `/usr/bin/env ruby -v` is not using the Application's ruby version but is instead using the version of Ruby that the buildpack is running on.

For CodeTriage, which currently runs Ruby 2.4.1

```
/usr/bin/env ruby -v:
  ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-linux]
/usr/bin/env which ruby:
  /tmp/tmp.CXcHvBwI9X/bin//ruby
/usr/bin/env echo $PATH:
  /tmp/tmp.CXcHvBwI9X/bin/:/app/bin:/app/vendor/bundle/bin:/app/vendor/bundle/ruby/2.4.0/bin:/usr/local/bin:/usr/bin:/bin:/app/.sprettur/bin/:/app/.sprettur/bin/


which ruby
  /app/bin/ruby
ruby -v
  ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]
GEM_PATH:
  vendor/bundle/ruby/2.4.0
PATH:
  /app/bin:/tmp/tmp.sGROjreAHz/bin/:/app/bin:/app/vendor/bundle/bin:/app/vendor/bundle/ruby/2.4.0/bin:/usr/local/bin:/usr/bin:/bin:/app/.sprettur/bin/:/app/.sprettur/bin/
```

Notice that `/usr/bin/env ruby -v` is different (and wrong) from `ruby -v`. This does not reproduce on `ci:debug`, only on a pipeline deploy. I have a debugging branch of the buildpack that can be used to get this output:

```
  "environments": {
    "test": {
      "buildpacks": [
       {"url": "https://github.com/heroku/heroku-buildpack-ruby#schneems/debug-bad-ruby"}
      ]
    }
  }
```

**Comment by schneems** [comment]
Turns out this `/usr/bin/env` isn't a problem. I don't know why but it causes no issues.

The root problem of getting a different ruby version in CI in this case was caused by spring

```
-----> Running test: bin/rspec
       Ignoring bcrypt-3.1.11 because its extensions are not built.  Try: gem pristine bcrypt --version 3.1.11
       Ignoring bluecloth-2.2.0 because its extensions are not built.  Try: gem pristine bluecloth --version 2.2.0
       Ignoring ffi-1.9.10 because its extensions are not built.  Try: gem pristine ffi --version 1.9.10
       Ignoring msgpack-1.0.0 because its extensions are not built.  Try: gem pristine msgpack --version 1.0.0
       Ignoring nio4r-1.2.1 because its extensions are not built.  Try: gem pristine nio4r --version 1.2.1
       Ignoring nokogiri-1.6.8.1 because its extensions are not built.  Try: gem pristine nokogiri --version 1.6.8.1
       Ignoring oj-2.18.0 because its extensions are not built.  Try: gem pristine oj --version 2.18.0
       Ignoring pg-0.18.3 because its extensions are not built.  Try: gem pristine pg --version 0.18.3
       Ignoring puma-3.8.2 because its extensions are not built.  Try: gem pristine puma --version 3.8.2
       Ignoring rbtrace-0.4.8 because its extensions are not built.  Try: gem pristine rbtrace --version 0.4.8
       Ignoring rusage-0.2.0 because its extensions are not built.  Try: gem pristine rusage --version 0.2.0
       Ignoring sassc-1.10.0 because its extensions are not built.  Try: gem pristine sassc --version 1.10.0
       Ignoring scout_apm-2.0.0.pre3 because its extensions are not built.  Try: gem pristine scout_apm --version 2.0.0.pre3
       Ignoring stackprof-0.2.9 because its extensions are not built.  Try: gem pristine stackprof --version 0.2.9
       Ignoring tunemygc-1.0.68 because its extensions are not built.  Try: gem pristine tunemygc --version 1.0.68
       Ignoring websocket-driver-0.6.4 because its extensions are not built.  Try: gem pristine websocket-driver --version 0.6.4
       /app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/definition.rb:473:in `validate_ruby!': Your Ruby version is 2.3.4, but your Gemfile specified ~> 2.4.1 (Bundler::RubyVersionMismatch)
       from /app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler.rb:93:in `setup'
       from /app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/setup.rb:20:in `<top (required)>'
       from /tmp/tmp.SQrcYHW6yr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
       from /tmp/tmp.SQrcYHW6yr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
       from /app/vendor/bundle/ruby/2.4.0/gems/spring-2.0.1/lib/spring/commands.rb:33:in `<module:Spring>'
       from /app/vendor/bundle/ruby/2.4.0/gems/spring-2.0.1/lib/spring/commands.rb:4:in `<top (required)>'
       from /tmp/tmp.SQrcYHW6yr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
       from /tmp/tmp.SQrcYHW6yr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
       from /app/vendor/bundle/ruby/2.4.0/gems/spring-2.0.1/lib/spring/application.rb:77:in `preload'
       from /app/vendor/bundle/ruby/2.4.0/gems/spring-2.0.1/lib/spring/application.rb:143:in `serve'
       from /app/vendor/bundle/ruby/2.4.0/gems/spring-2.0.1/lib/spring/application.rb:131:in `block in run'
       from /app/vendor/bundle/ruby/2.4.0/gems/spring-2.0.1/lib/spring/application.rb:125:in `loop'
       from /app/vendor/bundle/ruby/2.4.0/gems/spring-2.0.1/lib/spring/application.rb:125:in `run'
       from /app/vendor/bundle/ruby/2.4.0/gems/spring-2.0.1/lib/spring/application/boot.rb:19:in `<top (required)>'
       from /tmp/tmp.SQrcYHW6yr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
       from /tmp/tmp.SQrcYHW6yr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
       from -e:1:in `<main>'
-----> Ruby buildpack tests failed with exit status 1
``` 

Removing spring from `bin/rspec` fixed this issue:

```
unless ENV["HEROKU_TEST_RUN_ID"]
  begin
    load File.expand_path('../spring', __FILE__)
  rescue LoadError => e
    raise unless e.message.include?('spring')
  end
end
```

**Comment by justindowning** [comment]
@schneems You could also add `DISABLE_SPRING=true` to the CI env in `app.json`.

**Comment by schneems** [comment]
Thanks, that's a better way to do things.
