### ISSUE TITLE
Problem with downloading from Amazon

### ISSUE THREAD

**Issue by afuno** [heroku/heroku-buildpack-ruby#619]
There are no problems on the server with the Internet. Why can not I download Ruby? Awful download speed. Node.js hangs 20 minutes, but at least it is installed.

Four days ago everything was fine. I did not change the configuration.

.buildpacks:

```
https://github.com/heroku/heroku-buildpack-nodejs.git
https://github.com/heroku/heroku-buildpack-ruby.git
```

Full log:

```
Counting objects: 14, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (13/13), done.
Writing objects: 100% (14/14), 1.19 KiB | 0 bytes/s, done.
Total 14 (delta 9), reused 0 (delta 0)
remote: -----> Setting config vars
remote: GIT_REV: 536a18f230ba16510a4d58988e2c9363fa949861
-----> Cleaning up...
-----> Building my-first-app from herokuish...
-----> Adding BUILD_ENV to build environment...
-----> Warning: Multiple default buildpacks reported the ability to handle this app. The first buildpack in the list below will be used.
Detected buildpacks: multi ruby nodejs
-----> Multipack app detected
=====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-nodejs.git
=====> Detected Framework: Node.js

-----> Creating runtime environment

NPM_CONFIG_LOGLEVEL=error
NPM_CONFIG_PRODUCTION=true
NODE_VERBOSE=false
NODE_ENV=production
NODE_MODULES_CACHE=true

-----> Installing binaries
engines.node (package.json): 6.11.3
engines.npm (package.json): unspecified (use default)
engines.yarn (package.json): unspecified (use default)

Resolving node version 6.11.3...
Downloading and installing node 6.11.3...
Using default npm version: 3.10.10
Resolving yarn version 0.28.4...
Downloading and installing yarn (0.28.4)...
Installed yarn 0.28.4

-----> Restoring cache
Loading 2 from cacheDirectories (default):
- node_modules
- bower_components (not cached - skipping)

-----> Building dependencies
Installing node modules (yarn.lock)
yarn install v0.28.4
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.96s.

-----> Caching build
Clearing previous node cache
Saving 2 cacheDirectories (default):
- node_modules
- bower_components (nothing to cache)

-----> Build succeeded!
=====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-ruby.git
=====> Detected Framework: Ruby
Command: 'set -o pipefail; curl -L --fail --retry 5 --retry-delay 1 --connect-timeout 90 --max-time 60 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/cedar-14/ruby-2.3.4.tgz -s -o - | tar zxf - ' failed on attempt 1 of 3.
Command: 'set -o pipefail; curl -L --fail --retry 5 --retry-delay 1 --connect-timeout 90 --max-time 60 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/cedar-14/ruby-2.3.4.tgz -s -o - | tar zxf - ' failed on attempt 2 of 3.
remote: /tmp/buildpackJG7qP/lib/language_pack/shell_helpers.rb:58:in `block in run!': Command: 'set -o pipefail; curl -L --fail --retry 5 --retry-delay 1 --connect-timeout 90 --max-time 60 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/cedar-14/ruby-2.3.4.tgz -s -o - | tar zxf - ' failed unexpectedly: (LanguagePack::Fetcher::FetchError)
remote: 
remote: gzip: stdin: invalid compressed data--format violated
remote: tar: Unexpected EOF in archive
remote: tar: Unexpected EOF in archive
remote: tar: Error is not recoverable: exiting now
remote: from /tmp/buildpackJG7qP/lib/language_pack/shell_helpers.rb:52:in `times'
remote: from /tmp/buildpackJG7qP/lib/language_pack/shell_helpers.rb:52:in `run!'
remote: from /tmp/buildpackJG7qP/lib/language_pack/fetcher.rb:24:in `fetch_untar'
remote: from /tmp/buildpackJG7qP/lib/language_pack/installers/heroku_ruby_installer.rb:22:in `block in fetch_unpack'
remote: from /tmp/buildpackJG7qP/lib/language_pack/installers/heroku_ruby_installer.rb:16:in `chdir'
remote: from /tmp/buildpackJG7qP/lib/language_pack/installers/heroku_ruby_installer.rb:16:in `fetch_unpack'
remote: from /tmp/buildpackJG7qP/bin/support/download_ruby:14:in `<main>'
remote: <internal:gem_prelude>:4:in `require': cannot load such file -- rubygems.rb (LoadError)
remote: from <internal:gem_prelude>:4:in `<internal:gem_prelude>'
```

**Comment by schneems** [comment]
You need to open a support ticket help.heroku.com.

I recommend not using `.buildpacks` as the buildpack-multi had been deprecated for https://devcenter.heroku.com/articles/using-multiple-buildpacks-for-an-app

**Comment by afuno** [comment]
This month everything was downloading normally.
Up to this day.

The speed is shit again.
You do not have time to pay for the server or what?

**Comment by schneems** [comment]
Hey Anton, I still get emails if you delete the comments.
