### ISSUE TITLE
Generate or document RAILS_MASTER_KEY env

### ISSUE THREAD

**Issue by calebthompson** [heroku/heroku-buildpack-ruby#636]
For a vanilla new Rails 5.2.0-beta2 app, this happens during asset compilation (the first time we load the env). We should consider generating RAILS_MASTER_KEY in [`default_config_vars`](https://github.com/heroku/heroku-buildpack-ruby/blob/ce11aca649273103dfeed0ccc5880858be116aa6/lib/language_pack/rails41.rb#L25) for 5.2.x +.

```
remote: -----> Preparing app for Rails asset pipeline
remote:        Running: rake assets:precompile
remote:        rake aborted!
remote:        ActiveSupport::EncryptedFile::MissingKeyError: Missing encryption key to decrypt file with. Ask your team for your master key and write it to /tmp/build_9582d78162dd8c26569fbf3745f06d63/config/master.key or put it in the ENV['RAILS_MASTER_KEY'].
remote:        /tmp/build_9582d78162dd8c26569fbf3745f06d63/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/encrypted_file.rb:96:in `handle_missing_key'
remote:        /tmp/build_9582d78162dd8c26569fbf3745f06d63/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/encrypted_file.rb:37:in `key'
remote:        /tmp/build_9582d78162dd8c26569fbf3745f06d63/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/encrypted_file.rb:83:in `encryptor'
remote:        /tmp/build_9582d78162dd8c26569fbf3745f06d63/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/encrypted_file.rb:79:in `decrypt'
remote:        /tmp/build_9582d78162dd8c26569fbf3745f06d63/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/encrypted_file.rb:42:in `read'
remote:        /tmp/build_9582d78162dd8c26569fbf3745f06d63/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/encrypted_configuration.rb:20:in `read'
remote:        /tmp/build_9582d78162dd8c26569fbf3745f06d63/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/encrypted_configuration.rb:32:in `config'
remote:        /tmp/build_9582d78162dd8c26569fbf3745f06d63/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/encrypted_configuration.rb:37:in `options'
remote:        /tmp/build_9582d78162dd8c26569fbf3745f06d63/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/core_ext/module/delegation.rb:274:in `method_missing'
remote:        (erb):12:in `<main>'
remote:        /tmp/build_9582d78162dd8c26569fbf3745f06d63/vendor/bundle/ruby/2.4.0/gems/activestorage-5.2.0.beta2/lib/active_storage/engine.rb:55:in `block (2 levels) in <class:Engine>'
remote:        /tmp/build_9582d78162dd8c26569fbf3745f06d63/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/callbacks.rb:426:in `instance_exec'
remote:        /tmp/build_9582d78162dd8c26569fbf3745f06d63/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/callbacks.rb:426:in `block in make_lambda'
remote:        /tmp/build_9582d78162dd8c26569fbf3745f06d63/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
remote:        /tmp/build_9582d78162dd8c26569fbf3745f06d63/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
remote:        /tmp/build_9582d78162dd8c26569fbf3745f06d63/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/callbacks.rb:605:in `catch'
remote:        /tmp/build_9582d78162dd8c26569fbf3745f06d63/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/callbacks.rb:605:in `block in default_terminator'
remote:        /tmp/build_9582d78162dd8c26569fbf3745f06d63/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/callbacks.rb:199:in `block in halting'
remote:        /tmp/build_9582d78162dd8c26569fbf3745f06d63/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/callbacks.rb:513:in `block in invoke_before'
remote:        /tmp/build_9582d78162dd8c26569fbf3745f06d63/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/callbacks.rb:513:in `each'
remote:        /tmp/build_9582d78162dd8c26569fbf3745f06d63/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/callbacks.rb:513:in `invoke_before'
remote:        /tmp/build_9582d78162dd8c26569fbf3745f06d63/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/callbacks.rb:131:in `run_callbacks'
remote:        /tmp/build_9582d78162dd8c26569fbf3745f06d63/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/reloader.rb:89:in `prepare!'
remote:        /tmp/build_9582d78162dd8c26569fbf3745f06d63/vendor/bundle/ruby/2.4.0/gems/railties-5.2.0.beta2/lib/rails/application/finisher.rb:63:in `block in <module:Finisher>'
remote:        /tmp/build_9582d78162dd8c26569fbf3745f06d63/vendor/bundle/ruby/2.4.0/gems/railties-5.2.0.beta2/lib/rails/initializable.rb:32:in `instance_exec'
remote:        /tmp/build_9582d78162dd8c26569fbf3745f06d63/vendor/bundle/ruby/2.4.0/gems/railties-5.2.0.beta2/lib/rails/initializable.rb:32:in `run'
remote:        /tmp/build_9582d78162dd8c26569fbf3745f06d63/vendor/bundle/ruby/2.4.0/gems/railties-5.2.0.beta2/lib/rails/initializable.rb:61:in `block in run_initializers'
remote:        /tmp/build_9582d78162dd8c26569fbf3745f06d63/vendor/bundle/ruby/2.4.0/gems/railties-5.2.0.beta2/lib/rails/initializable.rb:60:in `run_initializers'
remote:        /tmp/build_9582d78162dd8c26569fbf3745f06d63/vendor/bundle/ruby/2.4.0/gems/railties-5.2.0.beta2/lib/rails/application.rb:360:in `initialize!'
remote:        /tmp/build_9582d78162dd8c26569fbf3745f06d63/config/environment.rb:5:in `<main>'
remote:        /tmp/build_9582d78162dd8c26569fbf3745f06d63/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
remote:        /tmp/build_9582d78162dd8c26569fbf3745f06d63/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
remote:        /tmp/build_9582d78162dd8c26569fbf3745f06d63/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:283:in `block in require'
remote:        /tmp/build_9582d78162dd8c26569fbf3745f06d63/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:249:in `load_dependency'
remote:        /tmp/build_9582d78162dd8c26569fbf3745f06d63/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:283:in `require'
remote:        /tmp/build_9582d78162dd8c26569fbf3745f06d63/vendor/bundle/ruby/2.4.0/gems/railties-5.2.0.beta2/lib/rails/application.rb:336:in `require_environment!'
remote:        /tmp/build_9582d78162dd8c26569fbf3745f06d63/vendor/bundle/ruby/2.4.0/gems/railties-5.2.0.beta2/lib/rails/application.rb:518:in `block in run_tasks_blocks'
remote:        /tmp/build_9582d78162dd8c26569fbf3745f06d63/vendor/bundle/ruby/2.4.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
remote:        /tmp/build_9582d78162dd8c26569fbf3745f06d63/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
```

**Comment by schneems** [comment]
We cannot randomly generate one or it will not work with the files they encrypted locally. 

If this key is required even if the feature is not being used it is a bug in rails and needs to be fixed.

**Comment by calebthompson** [comment]
Ah yes, good point. I assume I am "using" it by default as I've not specified otherwise.

**Comment by schneems** [comment]
If it’s enabled by default then it’s a bug.

**Comment by calebthompson** [comment]
The commands I've run so far are:

```
rails new rails52
bundle
```

My ~/.railsrc is:

```
--skip-bundle
--skip-test-unit
--database=postgresql
--skip-keeps
--skip-spring
```

**Comment by calebthompson** [comment]
Ok I opened https://github.com/rails/rails/issues/31283
