### ISSUE TITLE
rails build failed when using heroku/nodejs first

### ISSUE THREAD

**Issue by jerrywdlee** [heroku/heroku-buildpack-ruby#648]
I set buildpacks like
```
  1. heroku/nodejs
  2. heroku/ruby
```

and set `package.json` like 
```
  "engines": {
    "node": "8.9.x"
  },
```

As logs of node.js building, it said:
```
remote: -----> Installing binaries
remote:        engines.node (package.json):  8.9.x
remote:        engines.npm (package.json):   unspecified (use default)
remote:
remote:        Resolving node version 8.9.x...
remote:        Downloading and installing node 8.9.3...
remote:        Using default npm version: 5.5.1
```

but when rails build started, it show errors
```
remote:        rake aborted!
remote:        Uglifier::Error: Unexpected token: keyword (const). To use ES6 syntax, harmony mode must be enabled with Uglifier.new(:harmony => true).
remote:        /tmp/build_c300446586546dbcaf2ae814f64c9828/vendor/bundle/ruby/2.3.0/gems/uglifier-4.1.2/lib/uglifier.rb:236:in `parse_result'
remote:        /tmp/build_c300446586546dbcaf2ae814f64c9828/vendor/bundle/ruby/2.3.0/gems/uglifier-4.1.2/lib/uglifier.rb:218:in `run_uglifyjs'
remote:        /tmp/build_c300446586546dbcaf2ae814f64c9828/vendor/bundle/ruby/2.3.0/gems/uglifier-4.1.2/lib/uglifier.rb:168:in `compile'
remote:        /tmp/build_c300446586546dbcaf2ae814f64c9828/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/uglifier_compressor.rb:53:in `call'
remote:        /tmp/build_c300446586546dbcaf2ae814f64c9828/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/uglifier_compressor.rb:28:in `call'
remote:        /tmp/build_c300446586546dbcaf2ae814f64c9828/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
remote:        /tmp/build_c300446586546dbcaf2ae814f64c9828/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
remote:        /tmp/build_c300446586546dbcaf2ae814f64c9828/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
remote:        /tmp/build_c300446586546dbcaf2ae814f64c9828/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
remote:        /tmp/build_c300446586546dbcaf2ae814f64c9828/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
remote:        /tmp/build_c300446586546dbcaf2ae814f64c9828/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
remote:        /tmp/build_c300446586546dbcaf2ae814f64c9828/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
remote:        /tmp/build_c300446586546dbcaf2ae814f64c9828/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
remote:        /tmp/build_c300446586546dbcaf2ae814f64c9828/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
remote:        /tmp/build_c300446586546dbcaf2ae814f64c9828/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
remote:        /tmp/build_c300446586546dbcaf2ae814f64c9828/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:66:in `find_asset'
remote:        /tmp/build_c300446586546dbcaf2ae814f64c9828/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:73:in `find_all_linked_assets'
remote:        /tmp/build_c300446586546dbcaf2ae814f64c9828/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:142:in `block in find'
remote:        /tmp/build_c300446586546dbcaf2ae814f64c9828/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
remote:        /tmp/build_c300446586546dbcaf2ae814f64c9828/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:228:in `block in stat_tree'
remote:        /tmp/build_c300446586546dbcaf2ae814f64c9828/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
remote:        /tmp/build_c300446586546dbcaf2ae814f64c9828/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `each'
remote:        /tmp/build_c300446586546dbcaf2ae814f64c9828/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `stat_directory'
remote:        /tmp/build_c300446586546dbcaf2ae814f64c9828/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:227:in `stat_tree'
remote:        /tmp/build_c300446586546dbcaf2ae814f64c9828/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:231:in `block in stat_tree'
remote:        /tmp/build_c300446586546dbcaf2ae814f64c9828/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
remote:        /tmp/build_c300446586546dbcaf2ae814f64c9828/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `each'
remote:        /tmp/build_c300446586546dbcaf2ae814f64c9828/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `stat_directory'
remote:        /tmp/build_c300446586546dbcaf2ae814f64c9828/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:227:in `stat_tree'
remote:        /tmp/build_c300446586546dbcaf2ae814f64c9828/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:231:in `block in stat_tree'
remote:        /tmp/build_c300446586546dbcaf2ae814f64c9828/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
remote:        /tmp/build_c300446586546dbcaf2ae814f64c9828/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `each'
remote:        /tmp/build_c300446586546dbcaf2ae814f64c9828/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `stat_directory'
remote:        /tmp/build_c300446586546dbcaf2ae814f64c9828/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:227:in `stat_tree'
remote:        /tmp/build_c300446586546dbcaf2ae814f64c9828/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:105:in `each'
remote:        /tmp/build_c300446586546dbcaf2ae814f64c9828/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:105:in `block in logical_paths'
remote:        /tmp/build_c300446586546dbcaf2ae814f64c9828/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:104:in `each'
remote:        /tmp/build_c300446586546dbcaf2ae814f64c9828/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:104:in `logical_paths'
remote:        /tmp/build_c300446586546dbcaf2ae814f64c9828/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:140:in `find'
remote:        /tmp/build_c300446586546dbcaf2ae814f64c9828/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:185:in `compile'
remote:        /tmp/build_c300446586546dbcaf2ae814f64c9828/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
remote:        /tmp/build_c300446586546dbcaf2ae814f64c9828/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/rake/sprocketstask.rb:147:in `with_logger'
remote:        /tmp/build_c300446586546dbcaf2ae814f64c9828/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
remote:        /tmp/build_c300446586546dbcaf2ae814f64c9828/vendor/bundle/ruby/2.3.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
```

**Comment by dwightwatson** [comment]
I take it you're just using the asset pipeline, not Webpacker?

Looks simply that you're using ES6 code when you haven't correctly configured the asset pipeline to transpile it.

**Comment by josephpage** [comment]
You're 100% right @dwightwatson 
I confirm the issue isn't related to the buildpack.

@jerrywdlee I recommand you to check the config of your asset pipeline, and specially the config of the uglifier gem : https://github.com/lautis/uglifier#rails

I have had the issue, solved by adding this line to `config/environments/production.rb` : 
```
config.assets.js_compressor = Uglifier.new(harmony: true)
```
