### ISSUE TITLE
Bundler: failed to load command: webpack

### ISSUE THREAD

**Issue by joecorkerton** [heroku/heroku-buildpack-ruby#712]
Same issue as https://github.com/rails/webpacker/issues/1282.

I believe the ruby buildpack tries to install yarn and precompile assets when it detects webpacker, but this is not working. Currently it is necessary to also add the nodejs buildpack to successfully build a rails application with webpacker

**Comment by ssaunier** [comment]
Experiencing the same issue, it seems that the Node and Yarn engine versions are too old to support a `rails new --webpack` fresh install deployment.

Temporary fix: https://github.com/rails/webpacker/issues/739#issuecomment-327546884

**Comment by ssaunier** [comment]
Once this PR https://github.com/heroku/heroku-buildpack-ruby/pull/714 is merged and the buildpack released again, Rails 5.1 with Webpack 4 should work out of the box.

**Comment by schneems** [comment]
Merged and deployed, Let me know if this isn't resolved.

**Comment by joecorkerton** [comment]
@schneems I am still unable to build our app without the nodejs buildpack. Get the following error after it runs `rake assets:precompile`:

```
Using /tmp/build_8862381f297a97713ecf828e1e3eda5b/gh/config/webpacker.yml file for setting up webpack paths
       Compiling…
       Compilation failed:
       bundler: failed to load command: webpack (/tmp/build_8862381f297a97713ecf828e1e3eda5b/gh/vendor/bundle/ruby/2.5.0/bin/webpack)
       The latest bundler is 1.16.1, but you are currently running 1.15.2.
       To update, run `gem install bundler`
       
       Errno::ENOENT: No such file or directory - /tmp/build_8862381f297a97713ecf828e1e3eda5b/gh/node_modules/.bin/webpack
         /tmp/build_8862381f297a97713ecf828e1e3eda5b/gh/vendor/bundle/ruby/2.5.0/gems/webpacker-3.2.2/lib/webpacker/webpack_runner.rb:11:in `exec'
         /tmp/build_8862381f297a97713ecf828e1e3eda5b/gh/vendor/bundle/ruby/2.5.0/gems/webpacker-3.2.2/lib/webpacker/webpack_runner.rb:11:in `block in run'
         /tmp/build_8862381f297a97713ecf828e1e3eda5b/gh/vendor/bundle/ruby/2.5.0/gems/webpacker-3.2.2/lib/webpacker/webpack_runner.rb:10:in `chdir'
         /tmp/build_8862381f297a97713ecf828e1e3eda5b/gh/vendor/bundle/ruby/2.5.0/gems/webpacker-3.2.2/lib/webpacker/webpack_runner.rb:10:in `run'
         /tmp/build_8862381f297a97713ecf828e1e3eda5b/gh/vendor/bundle/ruby/2.5.0/gems/webpacker-3.2.2/lib/webpacker/runner.rb:6:in `run'
         /tmp/build_8862381f297a97713ecf828e1e3eda5b/gh/vendor/bundle/ruby/2.5.0/gems/webpacker-3.2.2/exe/webpack:8:in `<top (required)>'
         /tmp/build_8862381f297a97713ecf828e1e3eda5b/gh/vendor/bundle/ruby/2.5.0/bin/webpack:23:in `load'
         /tmp/build_8862381f297a97713ecf828e1e3eda5b/gh/vendor/bundle/ruby/2.5.0/bin/webpack:23:in `<top (required)>'
```

**Comment by thanhtruong1216** [comment]
I still have the issue too.
