### ISSUE TITLE
Exception causes Heroku Deploy to fail

### ISSUE THREAD

**Issue by adriancowham** [heroku/heroku-buildpack-ruby#815]
Hello,

We've been using heroku-buildpack-ruby for while and on Monday, 9/17, our deploys started failing.  Originally we used this link for the buildpack: https://github.com/heroku/heroku-buildpack-ruby.git. To workaround the issue we reverted to v193 by using this link: https://github.com/heroku/heroku-buildpack-ruby.git#v193. Irrespective of which version we use, our deploy encounters an exception. To be clear, this exception has existed in our deploy for a while. I'm not sure what's causing the exception but I don't think it's a heroku-buildpack-ruby issue. More likely, it's an issue with the `rinruby` gem. For context, here's some partial output from a successful build which includes the exception:

```
remote: -----> Detecting rails configuration
remote:        /tmp/build_0430f1e2bbde75343d02a3864f34b389/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/runtime.rb:85:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'rinruby'. (Bundler::GemRequireError)
remote:        Gem Load Error is: No such file or directory - R
remote:        Backtrace for gem load error is:
remote:        /tmp/build_0430f1e2bbde75343d02a3864f34b389/vendor/bundle/ruby/2.5.0/gems/rinruby-2.0.3/lib/rinruby.rb:164:in `popen'
remote:        /tmp/build_0430f1e2bbde75343d02a3864f34b389/vendor/bundle/ruby/2.5.0/gems/rinruby-2.0.3/lib/rinruby.rb:164:in `initialize'
remote:        /tmp/build_0430f1e2bbde75343d02a3864f34b389/vendor/bundle/ruby/2.5.0/gems/rinruby-2.0.3/lib/rinruby.rb:789:in `new'
remote:        /tmp/build_0430f1e2bbde75343d02a3864f34b389/vendor/bundle/ruby/2.5.0/gems/rinruby-2.0.3/lib/rinruby.rb:789:in `<top (required)>'
remote:        /tmp/build_0430f1e2bbde75343d02a3864f34b389/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/runtime.rb:82:in `require'
remote:        /tmp/build_0430f1e2bbde75343d02a3864f34b389/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/runtime.rb:82:in `block (2 levels) in require'
remote:        /tmp/build_0430f1e2bbde75343d02a3864f34b389/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/runtime.rb:77:in `each'
remote:        /tmp/build_0430f1e2bbde75343d02a3864f34b389/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/runtime.rb:77:in `block in require'
remote:        /tmp/build_0430f1e2bbde75343d02a3864f34b389/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/runtime.rb:66:in `each'
remote:        /tmp/build_0430f1e2bbde75343d02a3864f34b389/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/runtime.rb:66:in `require'
remote:        /tmp/build_0430f1e2bbde75343d02a3864f34b389/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler.rb:108:in `require'
remote:        /tmp/build_0430f1e2bbde75343d02a3864f34b389/config/application.rb:10:in `<top (required)>'
remote:        /tmp/build_0430f1e2bbde75343d02a3864f34b389/vendor/bundle/ruby/2.5.0/gems/railties-5.1.5/lib/rails/command/actions.rb:15:in `require'
remote:        /tmp/build_0430f1e2bbde75343d02a3864f34b389/vendor/bundle/ruby/2.5.0/gems/railties-5.1.5/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
remote:        /tmp/build_0430f1e2bbde75343d02a3864f34b389/vendor/bundle/ruby/2.5.0/gems/railties-5.1.5/lib/rails/commands/runner/runner_command.rb:27:in `perform'
remote:        /tmp/build_0430f1e2bbde75343d02a3864f34b389/vendor/bundle/ruby/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
remote:        /tmp/build_0430f1e2bbde75343d02a3864f34b389/vendor/bundle/ruby/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
remote:        /tmp/build_0430f1e2bbde75343d02a3864f34b389/vendor/bundle/ruby/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
remote:        /tmp/build_0430f1e2bbde75343d02a3864f34b389/vendor/bundle/ruby/2.5.0/gems/railties-5.1.5/lib/rails/command/base.rb:63:in `perform'
remote:        /tmp/build_0430f1e2bbde75343d02a3864f34b389/vendor/bundle/ruby/2.5.0/gems/railties-5.1.5/lib/rails/command.rb:44:in `invoke'
remote:        /tmp/build_0430f1e2bbde75343d02a3864f34b389/vendor/bundle/ruby/2.5.0/gems/railties-5.1.5/lib/rails/commands.rb:16:in `<top (required)>'
remote:        bin/rails:4:in `require'
remote:        bin/rails:4:in `<main>'
remote:        Bundler Error Backtrace:
remote:        	from /tmp/build_0430f1e2bbde75343d02a3864f34b389/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
remote:        	from /tmp/build_0430f1e2bbde75343d02a3864f34b389/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/runtime.rb:77:in `each'
remote:        	from /tmp/build_0430f1e2bbde75343d02a3864f34b389/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/runtime.rb:77:in `block in require'
remote:        	from /tmp/build_0430f1e2bbde75343d02a3864f34b389/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/runtime.rb:66:in `each'
remote:        	from /tmp/build_0430f1e2bbde75343d02a3864f34b389/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/runtime.rb:66:in `require'
remote:        	from /tmp/build_0430f1e2bbde75343d02a3864f34b389/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler.rb:108:in `require'
remote:        	from /tmp/build_0430f1e2bbde75343d02a3864f34b389/config/application.rb:10:in `<top (required)>'
remote:        	from /tmp/build_0430f1e2bbde75343d02a3864f34b389/vendor/bundle/ruby/2.5.0/gems/railties-5.1.5/lib/rails/command/actions.rb:15:in `require'
remote:        	from /tmp/build_0430f1e2bbde75343d02a3864f34b389/vendor/bundle/ruby/2.5.0/gems/railties-5.1.5/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
remote:        	from /tmp/build_0430f1e2bbde75343d02a3864f34b389/vendor/bundle/ruby/2.5.0/gems/railties-5.1.5/lib/rails/commands/runner/runner_command.rb:27:in `perform'
remote:        	from /tmp/build_0430f1e2bbde75343d02a3864f34b389/vendor/bundle/ruby/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
remote:        	from /tmp/build_0430f1e2bbde75343d02a3864f34b389/vendor/bundle/ruby/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
remote:        	from /tmp/build_0430f1e2bbde75343d02a3864f34b389/vendor/bundle/ruby/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
remote:        	from /tmp/build_0430f1e2bbde75343d02a3864f34b389/vendor/bundle/ruby/2.5.0/gems/railties-5.1.5/lib/rails/command/base.rb:63:in `perform'
remote:        	from /tmp/build_0430f1e2bbde75343d02a3864f34b389/vendor/bundle/ruby/2.5.0/gems/railties-5.1.5/lib/rails/command.rb:44:in `invoke'
remote:        	from /tmp/build_0430f1e2bbde75343d02a3864f34b389/vendor/bundle/ruby/2.5.0/gems/railties-5.1.5/lib/rails/commands.rb:16:in `<top (required)>'
remote:        	from bin/rails:4:in `require'
remote:        	from bin/rails:4:in `<main>
```

Like I said, the presence of this exception in v193 does not cause the deploy to fail. However, the presence of this exception does cause the deploy to fail on the master branch. I need to address this exception on my side but I'm wondering if the deploy failing due to the presence of an exception is a regression on your side. Thoughts?

Thanks.

**Comment by schneems** [comment]
Can you open up a support ticket so I can see your app? go to help.heroku.com search for "buildpack v193" and link this issue.

The only thing on master that isn't in v193 can be seen in the changelog https://github.com/heroku/heroku-buildpack-ruby/blob/master/CHANGELOG.md#master. It's only one change and it doesn't look to be related to that part of the code. Having access to your app and full deploy logs would help.

Based on this output

> No such file or directory - R

I'm guessing you have another buildpack before this one that installs R. It likely doesn't properly export their environment variables to the `export` folder. Here's an example of a PR that fixes that https://github.com/cyberdelia/heroku-geo-buildpack/pull/49/files#diff-c7b43338c09c3c9afd420fd8b6bb5198R110

This is documented here https://devcenter.heroku.com/articles/buildpack-api#composing-multiple-buildpacks.

If that's the case it's a change I can help get merged into the third party buildpack.

**Comment by adriancowham** [comment]
@schneems thanks for the reply, I created a GitHub support ticket, it's ticket #633244. I'm using 2 third party build packs, they are: 

https://github.com/virtualstaticvoid/heroku-buildpack-r#cedar-14
https://github.com/ryandotsmith/nginx-buildpack

I'll look at your suggestions and see if I can resolve my exception. Thanks again.

**Comment by adriancowham** [comment]
@schneems Thank you so much for your suggestions, exporting the relevant environment variables to the `export` dir addressed the exception and I was able to successfully deploy using the master branch of the `heroku-buildpack-ruby` buildpack.  I will close this issue.

Thanks again!
