### ISSUE TITLE
Error compiling buildpack

### ISSUE THREAD

**Issue by baelter** [heroku/heroku-buildpack-ruby#915]
This buildpack started failing recently with:

```

/tmp/buildpacks/e9338.../lib/github.rb:14:in `github_user_login': undefined method `[]' for nil:NilClass (NoMethodError)
	from /tmp/buildpacks/e9338.../lib/github.rb:8:in `login'
	from /tmp/buildpacks/e9338.../lib/github.rb:4:in `valid_login?'
	from /tmp/buildpacks/e9338.../bin/compile:42:in `<main>' ```

**Comment by baelter** [comment]
Reporten in wrong repo
